from enum import Enum


class CalcStates(Enum):
    FENCE_TYPE = 1
    FENCE_POPULAR_SPECS = 2
    FENCE_VARIANTS = 3
    FENCE_LENGTH = 4
    FENCE_ASK_ACCESSORIES = 5
    FENCE_ACCESSORIES = 6
    FENCE_ACCESSORIES_QUANTITY = 7
    FENCE_MORE_ACCESSORIES = 8
    NEED_GATES = 9
    GATE_TYPE = 10
    GATE_POPULAR_SPECS = 11
    GATE_VARIANTS = 12
    GATE_AUTOMATION = 13
    GATE_ACCESSORIES = 14
    GATE_MORE_ACCESSORIES = 15
    MOUNTING_TYPE = 16
    CONFIRM_CALC = 17
    FENCE_ACCESSORY_SPECS = 18
    GATE_ACCESSORIES_QUANTITY = 19
    GATE_ACCESSORY_SPECS = 20
    END = 99
